- name: Stop VM server
  ignore_errors: true
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    vmid: "{{ item }}"
    node: "{{ proxmox_node }}"
    state: stopped
    force: true
  loop: "{{ range(vm_server_id, vm_server_id + vm_count_server) | list }}"

- name: Stop VM worker
  ignore_errors: true
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    vmid: "{{ item }}"
    node: "{{ proxmox_node }}"
    state: stopped
    force: true
  loop: "{{ range(vm_worker_id, vm_worker_id + vm_count_worker) | list }}"